---
title: "Lab 3: GapMinder Data Exploration"
author: "Katie Duggan"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(dslabs)
library(tidyverse)
```

## Data

The GapMinder project was pioneered by Hans Rosling, who is famous for describing the prosperity of nations over time through famines, wars and other historic events with this beautiful data visualization in his 2006 TED Talk: The best stats you’ve ever seen.

```{r, echo = FALSE}
gap2011 <- gapminder %>% 
  as_tibble() %>% 
  filter(year == 2011)
```


## Life Expectancy

```{r, echo = FALSE}
ggplot(data = gap2011) +
  geom_point(mapping = aes(x = gdp, y = life_expectancy, color = continent, size = population))
```

```{r, echo = FALSE}
ggplot(data = gap2011) +
  geom_col(aes(x = continent, y = life_expectancy, fill = continent))
```


## Fertility

```{r, echo = FALSE}
ggplot(data = gap2011) +
  geom_point(mapping = aes(x = life_expectancy, y = fertility, color = continent))
```


## Infant Mortality

```{r, echo = FALSE}
ggplot(data = gap2011) +
  geom_point(mapping = aes(x = life_expectancy, y = infant_mortality, color = continent))
```

```{r, echo = FALSE}
ggplot(data = gap2011) +
  geom_col(aes(x = continent, y = infant_mortality, fill = continent))
```
